config/routes.rb
Rails.application.routes.draw do
  resources :gustos
  resources :menus
  resources :colas
  resources :mesas
  get 'welcome/index'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cola.rb
class Cola < ApplicationRecord
end

app/models/gusto.rb
class Gusto < ApplicationRecord
	has_many: menu 
end

app/models/has_gusto.rb
class HasGusto < ApplicationRecord
  belongs_to :cliente
  belongs_to :gustos
end

app/models/menu.rb
class Menu < ApplicationRecord

	belongs_to: gusto
end

app/models/mesa.rb
class Mesa < ApplicationRecord
end

app/models/place.rb
class Place < ApplicationRecord
end

app/models/space.rb
class Space < ApplicationRecord
end

app/models/table.rb
class Table < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/colas_controller.rb
class ColasController < ApplicationController
  before_action :set_cola, only: [:show, :edit, :update, :destroy]

  # GET /colas
  # GET /colas.json
  def index
    @colas = Cola.all
  end

  # GET /colas/1
  # GET /colas/1.json
  def show
  end

  # GET /colas/new
  def new
    @cola = Cola.new
  end

  # GET /colas/1/edit
  def edit
  end

  # POST /colas
  # POST /colas.json
  def create
    @cola = Cola.new(cola_params)

    respond_to do |format|
      if @cola.save
        format.html { redirect_to @cola, notice: 'Cola was successfully created.' }
        format.json { render :show, status: :created, location: @cola }
      else
        format.html { render :new }
        format.json { render json: @cola.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colas/1
  # PATCH/PUT /colas/1.json
  def update
    respond_to do |format|
      if @cola.update(cola_params)
        format.html { redirect_to @cola, notice: 'Cola was successfully updated.' }
        format.json { render :show, status: :ok, location: @cola }
      else
        format.html { render :edit }
        format.json { render json: @cola.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colas/1
  # DELETE /colas/1.json
  def destroy
    @cola.destroy
    respond_to do |format|
      format.html { redirect_to colas_url, notice: 'Cola was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cola
      @cola = Cola.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cola_params
      params.require(:cola).permit(:nombreCliente, :cantidadPersonas)
    end
end

app/controllers/gustos_controller.rb
class GustosController < ApplicationController
  before_action :set_gusto, only: [:show, :edit, :update, :destroy]

  # GET /gustos
  # GET /gustos.json
  def index
    @gustos = Gusto.all
  end

  # GET /gustos/1
  # GET /gustos/1.json
  def show
  end

  # GET /gustos/new
  def new
    @gusto = Gusto.new
  end

  # GET /gustos/1/edit
  def edit
  end

  # POST /gustos
  # POST /gustos.json
  def create
    @gusto = Gusto.new(gusto_params)

    respond_to do |format|
      if @gusto.save
        format.html { redirect_to @gusto, notice: 'Gusto was successfully created.' }
        format.json { render :show, status: :created, location: @gusto }
      else
        format.html { render :new }
        format.json { render json: @gusto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gustos/1
  # PATCH/PUT /gustos/1.json
  def update
    respond_to do |format|
      if @gusto.update(gusto_params)
        format.html { redirect_to @gusto, notice: 'Gusto was successfully updated.' }
        format.json { render :show, status: :ok, location: @gusto }
      else
        format.html { render :edit }
        format.json { render json: @gusto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gustos/1
  # DELETE /gustos/1.json
  def destroy
    @gusto.destroy
    respond_to do |format|
      format.html { redirect_to gustos_url, notice: 'Gusto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gusto
      @gusto = Gusto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gusto_params
      params.require(:gusto).permit(:Nombre)
    end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url, notice: 'Menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_params
      params.require(:menu).permit(:Nombre)
    end
end

app/controllers/mesas_controller.rb
class MesasController < ApplicationController
  before_action :set_mesa, only: [:show, :edit, :update, :destroy]

  # GET /mesas
  # GET /mesas.json
  def index
    @mesas = Mesa.all
  end

  # GET /mesas/1
  # GET /mesas/1.json
  def show
  end

  # GET /mesas/new
  def new
    @mesa = Mesa.new
  end

  # GET /mesas/1/edit
  def edit
  end

  # POST /mesas
  # POST /mesas.json
  def create
    @mesa = Mesa.new(mesa_params)

    respond_to do |format|
      if @mesa.save
        format.html { redirect_to @mesa, notice: 'Mesa was successfully created.' }
        format.json { render :show, status: :created, location: @mesa }
      else
        format.html { render :new }
        format.json { render json: @mesa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mesas/1
  # PATCH/PUT /mesas/1.json
  def update
    respond_to do |format|
      if @mesa.update(mesa_params)
        format.html { redirect_to @mesa, notice: 'Mesa was successfully updated.' }
        format.json { render :show, status: :ok, location: @mesa }
      else
        format.html { render :edit }
        format.json { render json: @mesa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mesas/1
  # DELETE /mesas/1.json
  def destroy
    @mesa.destroy
    respond_to do |format|
      format.html { redirect_to mesas_url, notice: 'Mesa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mesa
      @mesa = Mesa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mesa_params
      params.require(:mesa).permit(:ocupado, :integer, :numeroSillas, :sillas)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colas_helper.rb
module ColasHelper
end

app/helpers/gustos_helper.rb
module GustosHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/mesas_helper.rb
module MesasHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/colas/_form.html.erb
<%= form_with(model: cola, local: true) do |form| %>
  <% if cola.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cola.errors.count, "error") %> prohibited this cola from being saved:</h2>

      <ul>
      <% cola.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombreCliente %>
    <%= form.text_field :nombreCliente, id: :cola_nombreCliente %>
  </div>

  <div class="field">
    <%= form.label :cantidadPersonas %>
    <%= form.number_field :cantidadPersonas, id: :cola_cantidadPersonas %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/colas/edit.html.erb
<h1>Editing Cola</h1>

<%= render 'form', cola: @cola %>

<%= link_to 'Show', @cola %> |
<%= link_to 'Back', colas_path %>

app/views/colas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Colas</h1>

<table>
  <thead>
    <tr>
      <th>Nombrecliente</th>
      <th>Cantidadpersonas</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @colas.each do |cola| %>
      <tr>
        <td><%= cola.nombreCliente %></td>
        <td><%= cola.cantidadPersonas %></td>
        <td><%= link_to 'Show', cola %></td>
        <td><%= link_to 'Edit', edit_cola_path(cola) %></td>
        <td><%= link_to 'Destroy', cola, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cola', new_cola_path %>

app/views/colas/new.html.erb
<h1>New Cola</h1>

<%= render 'form', cola: @cola %>

<%= link_to 'Back', colas_path %>

app/views/colas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombrecliente:</strong>
  <%= @cola.nombreCliente %>
</p>

<p>
  <strong>Cantidadpersonas:</strong>
  <%= @cola.cantidadPersonas %>
</p>

<%= link_to 'Edit', edit_cola_path(@cola) %> |
<%= link_to 'Back', colas_path %>

app/views/gustos/_form.html.erb
<%= form_with(model: gusto, local: true) do |form| %>
  <% if gusto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gusto.errors.count, "error") %> prohibited this gusto from being saved:</h2>

      <ul>
      <% gusto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nombre %>
    <%= form.text_field :Nombre, id: :gusto_Nombre %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gustos/edit.html.erb
<h1>Editing Gusto</h1>

<%= render 'form', gusto: @gusto %>

<%= link_to 'Show', @gusto %> |
<%= link_to 'Back', gustos_path %>

app/views/gustos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gustos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gustos.each do |gusto| %>
      <tr>
        <td><%= gusto.Nombre %></td>
        <td><%= link_to 'Show', gusto %></td>
        <td><%= link_to 'Edit', edit_gusto_path(gusto) %></td>
        <td><%= link_to 'Destroy', gusto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gusto', new_gusto_path %>

app/views/gustos/new.html.erb
<h1>New Gusto</h1>

<%= render 'form', gusto: @gusto %>

<%= link_to 'Back', gustos_path %>

app/views/gustos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @gusto.Nombre %>
</p>

<%= link_to 'Edit', edit_gusto_path(@gusto) %> |
<%= link_to 'Back', gustos_path %>

app/views/menus/_form.html.erb
<%= form_with(model: menu, local: true) do |form| %>
  <% if menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nombre %>
    <%= form.text_field :Nombre, id: :menu_Nombre %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1>Editing Menu</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Menus</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menus.each do |menu| %>
      <tr>
        <td><%= menu.Nombre %></td>
        <td><%= link_to 'Show', menu %></td>
        <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
        <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menu', new_menu_path %>

app/views/menus/new.html.erb
<h1>New Menu</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @menu.Nombre %>
</p>

<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>

app/views/mesas/_form.html.erb
<%= form_with(model: mesa, local: true) do |form| %>
  <% if mesa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mesa.errors.count, "error") %> prohibited this mesa from being saved:</h2>

      <ul>
      <% mesa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ocupado %>
    <%= form.text_field :ocupado, id: :mesa_ocupado %>
  </div>

  <div class="field">
    <%= form.label :integer %>
    <%= form.text_field :integer, id: :mesa_integer %>
  </div>

  <div class="field">
    <%= form.label :numeroSillas %>
    <%= form.text_field :numeroSillas, id: :mesa_numeroSillas %>
  </div>

  <div class="field">
    <%= form.label :sillas %>
    <%= form.text_field :sillas, id: :mesa_sillas %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mesas/edit.html.erb
<h1>Editing Mesa</h1>

<%= render 'form', mesa: @mesa %>

<%= link_to 'Show', @mesa %> |
<%= link_to 'Back', mesas_path %>

app/views/mesas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mesas</h1>

<table>
  <thead>
    <tr>
      <th>Ocupado</th>
      <th>Integer</th>
      <th>Numerosillas</th>
      <th>Sillas</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mesas.each do |mesa| %>
      <tr>
        <td><%= mesa.ocupado %></td>
        <td><%= mesa.integer %></td>
        <td><%= mesa.numeroSillas %></td>
        <td><%= mesa.sillas %></td>
        <td><%= link_to 'Show', mesa %></td>
        <td><%= link_to 'Edit', edit_mesa_path(mesa) %></td>
        <td><%= link_to 'Destroy', mesa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mesa', new_mesa_path %>

app/views/mesas/new.html.erb
<h1>New Mesa</h1>

<%= render 'form', mesa: @mesa %>

<%= link_to 'Back', mesas_path %>

app/views/mesas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ocupado:</strong>
  <%= @mesa.ocupado %>
</p>

<p>
  <strong>Integer:</strong>
  <%= @mesa.integer %>
</p>

<p>
  <strong>Numerosillas:</strong>
  <%= @mesa.numeroSillas %>
</p>

<p>
  <strong>Sillas:</strong>
  <%= @mesa.sillas %>
</p>

<%= link_to 'Edit', edit_mesa_path(@mesa) %> |
<%= link_to 'Back', mesas_path %>

app/views/welcome/index.html.erb
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">Start Bootstrap</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#about">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#services">Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#portfolio">Portfolio</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <header class="masthead text-center text-white d-flex">
      <div class="container my-auto" style="color: black">
        <div class="row">
          <div class="col-lg-10 mx-auto">
            <h1 class="text-uppercase">
              <strong>Restaurante</strong>
            </h1>
            <hr>
          </div>
          <div class="col-lg-8 mx-auto">
            <p class="text-faded mb-5" style="color: black">Bienvenidos </p>
            <a class="btn btn-primary btn-xl js-scroll-trigger" href="#about">Solicitar mesa</a>
          </div>
        </div>
      </div>
    </header>